---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-idp-dcas-dev-v1-oauthclient
  failurePolicy: Fail
  name: moauthclient.kb.io
  rules:
  - apiGroups:
    - idp.dcas.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oauthclients
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-paas-dcas-dev-v1alpha1-appliedclusterversion
  failurePolicy: Fail
  name: mappliedclusterversion.kb.io
  rules:
  - apiGroups:
    - paas.dcas.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - appliedclusterversions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-paas-dcas-dev-v1alpha1-cluster
  failurePolicy: Fail
  name: mcluster.kb.io
  rules:
  - apiGroups:
    - paas.dcas.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-paas-dcas-dev-v1alpha1-clusteraddon
  failurePolicy: Fail
  name: mclusteraddon.kb.io
  rules:
  - apiGroups:
    - paas.dcas.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusteraddons
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-paas-dcas-dev-v1alpha1-clusteraddonbinding
  failurePolicy: Fail
  name: mclusteraddonbinding.kb.io
  rules:
  - apiGroups:
    - paas.dcas.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusteraddonbindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-paas-dcas-dev-v1alpha1-clusterversion
  failurePolicy: Fail
  name: mclusterversion.kb.io
  rules:
  - apiGroups:
    - paas.dcas.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterversions
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-idp-dcas-dev-v1-oauthclient
  failurePolicy: Fail
  name: voauthclient.kb.io
  rules:
  - apiGroups:
    - idp.dcas.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oauthclients
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-paas-dcas-dev-v1alpha1-appliedclusterversion
  failurePolicy: Fail
  name: vappliedclusterversion.kb.io
  rules:
  - apiGroups:
    - paas.dcas.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - appliedclusterversions
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-paas-dcas-dev-v1alpha1-cluster
  failurePolicy: Fail
  name: vcluster.kb.io
  rules:
  - apiGroups:
    - paas.dcas.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-paas-dcas-dev-v1alpha1-clusteraddon
  failurePolicy: Fail
  name: vclusteraddon.kb.io
  rules:
  - apiGroups:
    - paas.dcas.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusteraddons
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-paas-dcas-dev-v1alpha1-clusteraddonbinding
  failurePolicy: Fail
  name: vclusteraddonbinding.kb.io
  rules:
  - apiGroups:
    - paas.dcas.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusteraddonbindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-paas-dcas-dev-v1alpha1-clusterversion
  failurePolicy: Fail
  name: vclusterversion.kb.io
  rules:
  - apiGroups:
    - paas.dcas.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clusterversions
  sideEffects: None
