resources:
  - https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.5/core-components.yaml
  - provider-vcluster.yaml
images:
  - name: docker.io/loftsh/cluster-api-provider-vcluster
    newName: harbor.dcas.dev/docker.io/loftsh/cluster-api-provider-vcluster
  - name: registry.k8s.io/cluster-api/cluster-api-controller
    newName: harbor.dcas.dev/registry.k8s.io/cluster-api/cluster-api-controller
  - name: registry.k8s.io/cluster-api/kubeadm-bootstrap-controller
    newName: harbor.dcas.dev/registry.k8s.io/cluster-api/kubeadm-bootstrap-controller
  - name: registry.k8s.io/cluster-api/kubeadm-control-plane-controller
    newName: harbor.dcas.dev/registry.k8s.io/cluster-api/kubeadm-control-plane-controller
patches:
  - target:
      kind: Deployment
      name: capi-controller-manager
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args/2
        # needed to fix the following error
        # invalid argument "MachinePool=${EXP_MACHINE_POOL:=false},ClusterResourceSet=${EXP_CLUSTER_RESOURCE_SET:=false},ClusterTopology=${CLUSTER_TOPOLOGY:=false},RuntimeSDK=${EXP_RUNTIME_SDK:=false}" for "--feature-gates" flag: invalid value of MachinePool=${EXP_MACHINE_POOL:=false}, err: strconv.ParseBool: parsing "${EXP_MACHINE_POOL:=false}": invalid syntax
        value: "--feature-gates=MachinePool=false,ClusterResourceSet=false,ClusterTopology=false,RuntimeSDK=false"