ingress:
  enabled: false
  ingressClassName: {{ .Ingress.ClassName }}
  host: {{ .Ingress.Host }}
  {{- if .Ingress.Issuer }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Ingress.Issuer }}
  {{- end }}
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 12345