ingress:
  enabled: false
  ingressClassName: {{ .Ingress.ClassName }}
  host: {{ .Ingress.Host }}
  {{- if .Ingress.Issuer }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Ingress.Issuer }}
  {{- end }}
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 12345
vcluster:
  extraArgs:
    - --kube-apiserver-arg="--oidc-issuer-url={{ .IDP.URL }}"
    - --kube-apiserver-arg="--oidc-client-id={{ .IDP.ClientID }}"
    - --kube-apiserver-arg="--oidc-username-claim=email"
    - --kube-apiserver-arg="--oidc-username-prefix=-"
    - --kube-apiserver-arg="--oidc-groups-prefix=oidc:"
    - --kube-apiserver-arg="--oidc-ca-file=/var/run/secrets/dcas.dev/tls/ca.crt"
  volumeMounts:
    - name: data
      mountPath: /data
    - name: tls
      mountPath: /var/run/secrets/dcas.dev/tls
      readOnly: true
volumes:
  - name: tls
    secret:
      secretName: {{ .Ingress.TLSSecretName }}
storage:
  persistence: true
  {{- if .Storage.Size }}
  size: "{{ .Storage.Size }}Gi"
  {{- end }}
  {{- if .Storage.StorageClassName }}
  className: {{ .Storage.StorageClassName }}
  {{- end }}