ingress:
  enabled: false
{{- if .OpenShift }}
securityContext: null
{{- else }}
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 12345
{{- end }}
sync:
  ingresses:
    enabled: true
vcluster:
  image: {{ .Image }}
  extraArgs:
    - --kube-apiserver-arg="--oidc-issuer-url={{ .IDP.URL }}"
    - --kube-apiserver-arg="--oidc-client-id=$(DEX_CLIENT_ID)"
    - --kube-apiserver-arg="--oidc-username-claim=email"
    - --kube-apiserver-arg="--oidc-username-prefix=-"
    - --kube-apiserver-arg="--oidc-groups-prefix=oidc:"
    - --kube-apiserver-arg="--oidc-ca-file=/var/run/secrets/dcas.dev/tls/ca.crt"
  volumeMounts:
    - name: data
      mountPath: /data
    - name: tls
      mountPath: /var/run/secrets/dcas.dev/tls
      readOnly: true
  env:
    - name: DEX_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: "{{ .Name }}-dex"
          key: client_id
volumes:
  - name: tls
    secret:
      secretName: {{ .Ingress.TLSSecretName }}
storage:
  persistence: true
  {{- if .Storage.Size }}
  size: "{{ .Storage.Size }}Gi"
  {{- end }}
  {{- if .Storage.StorageClassName }}
  className: {{ .Storage.StorageClassName }}
  {{- end }}
coredns:
{{- if .HA }}
  replicas: 2
{{- else }}
  replicas: 1
{{- end }}
{{- if .OpenShift }}
openshift:
  enabled: true
{{- end }}
plugin:
  glass-hook:
    image: dev.local/kube-glass/vcluster-plugin-hooks:latest
    imagePullPolicy: Never
    env:
      - name: VCLUSTER_CLUSTER_DOMAIN
        value: "{{ .Ingress.Host }}"
  glass-sync:
    image: dev.local/kube-glass/vcluster-plugin-sync:latest
    imagePullPolicy: Never
    env:
      - name: VCLUSTER_CLUSTER_NAME
        value: "{{ .Name }}"
      - name: __GLASS_CLUSTER_URL__
        value: "{{ .Ingress.Host }}"
      - name: __GLASS_INGRESS_CLASS__
        value: "{{ .Ingress.ClassName }}"
      - name: __GLASS_DEX_URL__
        value: "{{ .IDP.URL }}"
      - name: __GLASS_DEX_CLIENT_ID__
        valueFrom:
          secretKeyRef:
            name: "{{ .Name }}-dex"
            key: client_id
      - name: __GLASS_DEX_CLIENT_SECRET__
        valueFrom:
          secretKeyRef:
            name: "{{ .Name }}-dex"
            key: client_secret
    rbac:
      role:
        extraRules:
          - apiGroups: ["paas.dcas.dev"]
            resources: ["tenants", "clusters", "clusteraddons"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["paas.dcas.dev"]
            resources: ["clusteraddonbindings"]
            verbs: ["get", "list", "watch", "update", "patch"]
          - apiGroups: ["paas.dcas.dev"]
            resources: ["clusters/status", "clusteraddonbindings/status"]
            verbs: ["get", "update", "patch"]