apiVersion: skaffold/v3
kind: Config
metadata:
  name: apiserver
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: dev.local/kube-glass/apiserver
      ko:
        fromImage: harbor.dcas.dev/gcr.io/distroless/static:nonroot
        main: ./cmd/apiserver/
        dependencies:
          paths:
            - cmd/
            - internal/
            - pkg/
            - go.mod
            - go.sum
  local:
    push: false
manifests:
  kustomize:
    paths:
      - k8s/
deploy:
  kubectl: {}
  kubeContext: minikube
