apiVersion: skaffold/v3
kind: Config
metadata:
  name: apiserver
build:
  artifacts:
    - image: dev.local/kube-glass/apiserver
      ko:
        fromImage: harbor.dcas.dev/gcr.io/distroless/static:nonroot
        main: ./cmd/apiserver/
        dependencies:
          paths:
            - cmd/
            - internal/
            - pkg/
            - go.mod
            - go.sum
  local:
    push: false
manifests:
  kustomize:
    paths:
      - k8s/
  helm:
    releases:
      - name: auto-deploy-app
        remoteChart: https://av1o.gitlab.io/charts/auto-deploy-app-0.15.4.tgz
        valuesFiles:
          - k8s/values.yaml
        namespace: glass-system
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO}}'
          image.tag: '{{.IMAGE_TAG}}'
        createNamespace: true
        upgradeOnChange: true
deploy:
  helm: {}
  kubeContext: minikube
