apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: apiserver
build:
  artifacts:
  - image: dev.local/kube-glass/apiserver
    custom:
      buildCommand: ./hack/build.sh
#    ko:
#      main: ./cmd/apiserver/
#      dependencies:
#        paths:
#          - cmd/
#          - internal/
#          - go.mod
#          - go.sum
  local:
    push: false
deploy:
  kubeContext: minikube
  kustomize:
    paths:
      - k8s/
  helm:
    releases:
      - name: auto-deploy-app
        remoteChart: /home/django/.cache/helm/repository/auto-deploy-app-0.15.3.tgz
#        remoteChart: https://av1o.gitlab.io/charts/auto-deploy-app-0.15.3.tgz
        namespace: glass-system
        createNamespace: true
        upgradeOnChange: true
        valuesFiles:
          - k8s/values.yaml
        imageStrategy:
          helm: {}
        artifactOverrides:
          image: dev.local/kube-glass/apiserver