// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cluster struct {
	ID     string `json:"id"`
	Tenant string `json:"tenant"`
}

type NewTenant struct {
	Name      string `json:"name"`
	OidcGroup string `json:"oidcGroup"`
}

type Tenant struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	OidcGroup string `json:"oidcGroup"`
}
