namespace: glass-system
resources:
  - addons.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: glass-addon-dashboard-okd
    files:
      - dashboard-okd/namespace.yaml
      - dashboard-okd/secret.yaml
      - dashboard-okd/patch-test.yaml
      - dashboard-okd/kustomization.yaml
  - name: glass-addon-dashboard-k8s
    files:
      - dashboard-k8s/ingress.yaml
      - dashboard-k8s/secret.yaml
      - dashboard-k8s/kustomization.yaml
  - name: glass-addon-podinfo
    files:
      - podinfo/namespace.yaml
      - podinfo/ingress.yaml
      - podinfo/kustomization.yaml