{{- if .Values.vkp.clusterVersions.default.enabled }}
apiVersion: paas.dcas.dev/v1alpha1
kind: ClusterVersion
metadata:
  name: vkp-25-3-rapid
spec:
  image:
    {{- if .Values.global.imageRegistry | default .Values.vkp.clusterVersions.image.registry }}
    registry: {{ .Values.global.imageRegistry | default .Values.vkp.clusterVersions.image.registry }}
    {{- end }}
    repository: {{ .Values.vkp.clusterVersions.image.repository }}
    tag: v1.25.3-k3s1
  track: Rapid
---
apiVersion: paas.dcas.dev/v1alpha1
kind: ClusterVersion
metadata:
  name: vkp-26-0-rapid
spec:
  image:
    {{- if .Values.global.imageRegistry | default .Values.vkp.clusterVersions.image.registry }}
    registry: {{ .Values.global.imageRegistry | default .Values.vkp.clusterVersions.image.registry }}
    {{- end }}
    repository: {{ .Values.vkp.clusterVersions.image.repository }}
    tag: v1.26.0-k3s1
  track: Rapid
{{- end }}