{{- if .Values.vkp.clusterVersions.default.enabled }}
apiVersion: paas.dcas.dev/v1alpha1
kind: ClusterVersion
metadata:
  name: vkp-24-7-regular
spec:
  image:
    {{- if .Values.global.imageRegistry | default .Values.vkp.clusterVersions.image.registry }}
    registry: {{ .Values.global.imageRegistry | default .Values.vkp.clusterVersions.image.registry }}
    {{- end }}
    repository: {{ .Values.vkp.clusterVersions.image.repository }}
    tag: v1.24.7-k3s1
  track: Regular
---
apiVersion: paas.dcas.dev/v1alpha1
kind: ClusterVersion
metadata:
  name: vkp-25-5-regular
spec:
  image:
    {{- if .Values.global.imageRegistry | default .Values.vkp.clusterVersions.image.registry }}
    registry: {{ .Values.global.imageRegistry | default .Values.vkp.clusterVersions.image.registry }}
    {{- end }}
    repository: {{ .Values.vkp.clusterVersions.image.repository }}
    tag: v1.25.5-k3s1
  track: Regular
---
apiVersion: paas.dcas.dev/v1alpha1
kind: ClusterVersion
metadata:
  name: vkp-26-4-regular
spec:
  image:
    {{- if .Values.global.imageRegistry | default .Values.vkp.clusterVersions.image.registry }}
    registry: {{ .Values.global.imageRegistry | default .Values.vkp.clusterVersions.image.registry }}
    {{- end }}
    repository: {{ .Values.vkp.clusterVersions.image.repository }}
    tag: v1.26.4-k3s1
  track: Regular
{{- end }}