global:
  ingress:
    annotations: {}
    domain: 192-168-49-2.nip.io # USER - set me!
    ingressClassName: "" # USER - set me!
    tlsSecret: ""

prometheus:
  url: ""

idp:
  existingSecret: ""
  clientSecret: ""
  cookieSecret: ""
  connectors: # USER - set me!
    - id: mock
      name: Mock
      type: mockCallback

api:
  logLevel: 0
  image: todo
web:
  image: todo
oauthProxy:
  image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0-amd64

dex:
  envVars:
    - name: CLIENT_SECRET_VKP
      value: "" # USER - set me!
  configSecret:
    create: false
    name: dex
  grpc:
    enabled: true
  ingress:
    enabled: false