global:
  # -- Custom Certificate Authority to use
  # for all components. Generally this should contain
  # a single CA, but it can support many.
  caSecret: ""
  ingress:
    # -- Annotations to add to all ingress resources
    # (e.g. cert-manager issuers)
    annotations: {}
    # -- Base domain for components to be hosted on.
    domain: example.org
    # -- IngressClass that will be used to implement the Ingress.
    ingressClassName: ""
    # -- TLS certificate to use for ingress. Doesn't need to exist
    # if cert-manager is creating it (assuming
    # you have set your annotations correctly).
    tlsSecret: tls-vkp

prometheus:
  # -- Url to the prometheus instance.
  # Embedded environment variables will be expanded
  # e.g. `http://$PROMETHEUS_USERNAME:$PROMETHEUS_PASSWORD@prometheus:9090`
  url: ""
  # -- If set, overrides the default metrics.
#  metrics: []
  # -- Additional metrics to show on the cluster overview
  # page.
  extraMetrics: []

idp:
  # -- Existing secret to load credentials from.
  # Must contain `DEX_CLIENT_SECRET` and `OAUTH2_PROXY_COOKIE_SECRET` keys
  existingSecret: ""
  # -- OIDC client secret that VKP components will use to authenticate to Dex
  clientSecret: ""
  # -- Secret to use for the Oauth proxy cookies
  cookieSecret: ""
  # -- Dex connectors that VKP will delegate authentication
  # to.
  # https://dexidp.io/docs/connectors/
  connectors:
    - id: mock
      name: Mock
      type: mockCallback

api:
  # -- APIServer image
  image: ghcr.io/vkp-app/vkp/apiserver:main
  # -- APIServer image pull policy
  imagePullPolicy: IfNotPresent
#  extraEnv: []
#  extraArgs: []
#  resources: {}
#  podSecurityContext: {}
#  containerSecurityContext: {}
web:
  # -- Web image
  image: ghcr.io/vkp-app/vkp/web:main
  # -- Web image pull policy
  imagePullPolicy: IfNotPresent
#  extraEnv: []
#  resources: {}
#  podSecurityContext: {}
#  containerSecurityContext: {}
oauthProxy:
  # -- Oauth proxy image
  image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0-amd64
  # -- Oauth proxy image pull policy
  imagePullPolicy: IfNotPresent
#  extraEnv: []
#  extraArgs: []
#  resources: {}
#  containerSecurityContext: {}

dex:
  # -- Dex image
  image: ghcr.io/dexidp/dex:v2.35.3
  # -- Dex image pull policy
  imagePullPolicy: IfNotPresent
  ingress:
    # -- Dex TLS certificate
    tlsSecret: tls-dex
#  extraEnv: []
#  extraArgs: []
#  resources: {}
#  podSecurityContext: {}
#  containerSecurityContext: {}