global:
  caSecret: ""
  ingress:
    annotations: {}
    domain: example.org
    ingressClassName: ""
    tlsSecret: tls-vkp

prometheus:
  # url to the prometheus instance.
  # embedded environment variables will be expanded
  # e.g. http://$PROMETHEUS_USERNAME:$PROMETHEUS_PASSWORD@promtheus:9090
  url: ""

idp:
  existingSecret: ""
  clientSecret: ""
  cookieSecret: ""
  connectors:
    - id: mock
      name: Mock
      type: mockCallback

api:
  image: ghcr.io/vkp-app/vkp/apiserver:main
  imagePullPolicy: IfNotPresent
#  extraArgs: []
#  resources: {}
#  podSecurityContext: {}
#  containerSecurityContext: {}
web:
  image: ghcr.io/vkp-app/vkp/web:main
  imagePullPolicy: IfNotPresent
#  resources: {}
#  podSecurityContext: {}
#  containerSecurityContext: {}
oauthProxy:
  image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0-amd64
  imagePullPolicy: IfNotPresent
#  extraArgs: []
#  resources: {}
#  containerSecurityContext: {}

dex:
  image: ghcr.io/dexidp/dex:v2.35.3
  imagePullPolicy: IfNotPresent
#  extraArgs: []
#  resources: {}
#  podSecurityContext: {}
#  containerSecurityContext: {}