global:
  # -- Global container image registry. Takes priority of any `image.registry` definitions.
  imageRegistry: ""
  # -- Global container registry secret names as an array.
  imagePullSecrets: []
  # -- Custom Certificate Authority to use
  # for all components. Generally this should contain
  # a single CA, but it can support many.
  caSecret: ""
  ingress:
    # -- Annotations to add to all ingress resources
    # (e.g. cert-manager issuers)
    annotations: {}
    # -- Base domain for components to be hosted on.
    domain: example.org
    # -- IngressClass that will be used to implement the Ingress.
    ingressClassName: ""
    # -- TLS certificate to use for ingress. Doesn't need to exist
    # if cert-manager is creating it (assuming
    # you have set your annotations correctly).
    tlsSecret: tls-vkp

prometheus:
  # -- Url to the prometheus instance.
  # Embedded environment variables will be expanded
  # e.g. `http://$PROMETHEUS_USERNAME:$PROMETHEUS_PASSWORD@prometheus:9090`
  url: ""
  # -- If set, overrides the default metrics.
#  metrics: []
  # -- Additional metrics to show on the cluster overview
  # page.
  extraMetrics: []

idp:
  # -- Existing secret to load credentials from.
  # Must contain `DEX_CLIENT_SECRET` and `OAUTH2_PROXY_COOKIE_SECRET` keys
  existingSecret: ""
  # -- OIDC client secret that VKP components will use to authenticate to Dex
  clientSecret: ""
  # -- Secret to use for the Oauth proxy cookies
  cookieSecret: ""
  # -- Dex connectors that VKP will delegate authentication
  # to.
  # https://dexidp.io/docs/connectors/
  connectors:
    - id: mock
      name: Mock
      type: mockCallback

api:
  image:
    # -- APIServer image registry
    registry: ghcr.io
    # -- API Server image repository
    repository: vkp-app/vkp/apiserver
    # -- APIServer image tag (defaults to .Chart.AppVersion)
    tag: ""
  # -- APIServer image pull policy
  imagePullPolicy: IfNotPresent
#  extraEnv: []
#  extraArgs: []
#  resources: {}
#  podSecurityContext: {}
#  containerSecurityContext: {}
web:
  image:
    # -- Web image registry
    registry: ghcr.io
    # -- Web image repository
    repository: vkp-app/vkp/web
    # -- Web image tag (defaults to .Chart.AppVersion)
    tag: ""
  # -- Web image pull policy
  imagePullPolicy: IfNotPresent
#  extraEnv: []
#  resources: {}
#  podSecurityContext: {}
#  containerSecurityContext: {}
oauthProxy:
  # -- Whether to use embedded static files (e.g. CSS). Required to work without an internet connection.
  embedStaticResources: false
  image:
    # -- Oauth proxy image registry
    registry: quay.io
    # -- Oauth proxy image repository
    repository: oauth2-proxy/oauth2-proxy
    # -- Oauth proxy image tag
    tag: v7.4.0-amd64
  # -- Oauth proxy image pull policy
  imagePullPolicy: IfNotPresent
#  extraEnv: []
#  extraArgs: []
#  resources: {}
#  containerSecurityContext: {}

metrics_proxy:
  image:
    # -- Metrics Proxy image registry
    registry: ghcr.io
    # -- Metrics Proxy image repository
    repository: vkp-app/vkp/metrics-proxy
    # -- Metrics Proxy image tag
    tag: ""
  # -- Metrics Proxy image pull policy
  imagePullPolicy: IfNotPresent
#  extraEnv: []
#  resources: {}
#  podSecurityContext: {}
#  containerSecurityContext: {}

dex:
  image:
    # -- Dex image registry
    registry: ghcr.io
    # -- Dex image repository
    repository: vkp-app/vkp/dex
    # -- Dex image tag
    tag: ""
  # -- Dex image pull policy
  imagePullPolicy: IfNotPresent
  ingress:
    # -- Dex host. Always includes the `global.ingress.domain` as a suffix (e.g. setting this to "foo" will result in "foo.example.org").
    host: dex
    # -- Dex TLS certificate
    tlsSecret: tls-dex
#  extraEnv: []
#  extraArgs: []
#  resources: {}
#  podSecurityContext: {}
#  containerSecurityContext: {}

vkp:
  # -- Console host. Always includes the `global.ingress.domain` as a suffix (e.g. setting this to "foo" will result in "foo.example.org").
  consoleHost: vkp
  clusterVersions:
    default:
      # -- Install default ClusterVersions. Disable to supply your own.
      enabled: false
    image:
      # -- Container registry to pull images from.
      registry: docker.io
      # -- Repository containing cluster images.
      repository: rancher/k3s
  certificates:
    # -- Name of the Cert Manager namespace that we can use to create ClusterIssuer's
    certManagerNamespace: cert-manager
    customIssuer:
      # -- Disables the default self-signed issuer used to bootstrap the VKP Certificate Authority.
      enabled: false
      # -- Name of the Issuer/ClusterIssuer to bootstrap from.
      name: ""
      # -- Kind (Issuer/ClusterIssuer) of the resource to bootstrap from.
      kind: Issuer