# This patch inject a sidecar container which is a HTTP proxy for the
# controller manager, it performs RBAC authorization against the Kubernetes API using SubjectAccessReviews.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: RELATED_IMAGE_PLUGIN_SYNC
              value: ghcr.io/vkp-app/vkp/vcluster-plugin-sync:main
            - name: RELATED_IMAGE_PLUGIN_HOOKS
              value: ghcr.io/vkp-app/vkp/vcluster-plugin-hooks:main
            - name: PASS_PLUGIN_PULL_POLICY
              value: Always