# permissions for end users to edit clusterversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterversion-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterversion-editor-role
rules:
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusterversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusterversions/status
  verbs:
  - get
