# permissions to emit custom events.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-recorder-role
rules:
  - apiGroups:
    - ""
    resources:
      - events
    verbs:
      - create
