# permissions for end users to view oauthclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: oauthclient-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: oauthclient-viewer-role
rules:
- apiGroups:
  - idp.dcas.dev
  resources:
  - oauthclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - idp.dcas.dev
  resources:
  - oauthclients/status
  verbs:
  - get
