---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - idp.dcas.dev
  resources:
  - oauthclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - idp.dcas.dev
  resources:
  - oauthclients/finalizers
  verbs:
  - update
- apiGroups:
  - idp.dcas.dev
  resources:
  - oauthclients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - vclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.dcas.dev
  resources:
  - appliedclusterversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.dcas.dev
  resources:
  - appliedclusterversions/finalizers
  verbs:
  - update
- apiGroups:
  - paas.dcas.dev
  resources:
  - appliedclusterversions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusteraddonbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusteraddonbindings/finalizers
  verbs:
  - update
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusteraddonbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusteraddons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusteraddons/finalizers
  verbs:
  - update
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusteraddons/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusterversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusterversions/finalizers
  verbs:
  - update
- apiGroups:
  - paas.dcas.dev
  resources:
  - clusterversions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - paas.dcas.dev
  resources:
  - tenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.dcas.dev
  resources:
  - tenants/finalizers
  verbs:
  - update
- apiGroups:
  - paas.dcas.dev
  resources:
  - tenants/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - postgres-operator.crunchydata.com
  resources:
  - postgresclusters
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
