namespace: monitoring
resources:
  - namespace.yaml
helmCharts:
  - name: kube-prometheus-stack
    namespace: monitoring
    releaseName: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 42.2.1
    valuesFile: values.yaml