fullnameOverride: prometheus-olm
global:
  rbac:
    pspEnabled: false
    createAggregateClusterRoles: true
grafana:
  enabled: false
prometheus-node-exporter:
  image:
    registry: harbor.dcas.dev/quay.io
  prometheus:
    monitor:
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: ^(.*)$
          targetLabel: instance
          replacement: $1
          action: replace
  rbac:
    pspEnabled: false
kubeStateMetrics:
  image:
    repository: harbor.dcas.dev/k8s.gcr.io/kube-state-metrics/kube-state-metrics
kube-state-metrics:
  metricLabelsAllowlist:
    - pods=[*]
    - deployments=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance]
  prometheus:
    monitor:
      metricRelabelings:
        - action: labeldrop
          regex: instance
      relabelings:
        - action: labeldrop
          regex: pod
prometheusOperator:
  admissionWebhooks:
    patch:
      podAnnotations:
        linkerd.io/inject: disabled
      image:
        registry: harbor.dcas.dev/quay.io
  image:
    registry: harbor.dcas.dev/quay.io
  prometheusConfigReloader:
    image:
      registry: harbor.dcas.dev/quay.io
  thanosImage:
    registry: harbor.dcas.dev/quay.io
alertmanager:
  alertmanagerSpec:
    image:
      registry: harbor.dcas.dev/quay.io
prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: iss-kube
    hosts:
      - prometheus.192-168-49-2.nip.io
    pathType: ImplementationSpecific
    tls:
      - secretName: prometheus-general-tls
        hosts:
          - prometheus.192-168-49-2.nip.io
  prometheusSpec:
    image:
      registry: harbor.dcas.dev/quay.io
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    probeSelectorNilUsesHelmValues: false
    probeSelector: {}
#    retention: 12h
#    storageSpec:
#      volumeClaimTemplate:
#        spec:
#          accessModes: ["ReadWriteOnce"]
#          resources:
#            requests:
#              storage: 5Gi
kubelet:
  serviceMonitor:
    resource: true
    resourcePath: /metrics/resource
    resourceMetricRelabelings:
      - action: keep
        regex: container_cpu_usage_seconds_total|container_memory_working_set_bytes|scrape_error
        sourceLabels:
          - __name__
      - action: replace
        replacement: $1
        sourceLabels:
          - __name__
        targetLabel: __name__
    cAdvisorMetricRelabelings:
      - action: drop
        regex: container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)
        sourceLabels:
          - __name__
      - action: drop
        regex: (container_spec_.*|container_file_descriptors|container_sockets|container_threads_max|container_threads|container_start_time_seconds|container_last_seen);;
        sourceLabels:
          - __name__
          - pod
          - namespace
      - action: drop
        regex: (container_blkio_device_usage_total);.+
        sourceLabels:
          - __name__
          - container
      - action: drop
        regex: container_memory_failures_total
        sourceLabels:
          - __name__
      - regex: container_fs_usage_bytes
        replacement: "true"
        sourceLabels:
          - __name__
        targetLabel: __tmp_keep_metric
      - action: drop
        regex: ;(container_fs_.*);.+
        sourceLabels:
          - __tmp_keep_metric
          - __name__
          - container
      - action: labeldrop
        regex: __tmp_keep_metric