resources:
  - namespace.yaml
  - https://github.com/CrunchyData/postgres-operator-examples//kustomize/install/default
images:
    # since the k8s v1.25 compatible fix has not been released yet, this image is used for now.
    # https://github.com/CrunchyData/postgres-operator/issues/3365
  - name: registry.developers.crunchydata.com/crunchydata/postgres-operator
    newName: harbor.dcas.dev/quay.io/myan/postgres-operator
    newTag: ubi8-k8s.1.25
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: pgo
    spec:
      template:
        spec:
          containers:
            - name: operator
              env:
                - name: CHECK_FOR_UPGRADES
                  value: "false"
                - name: CRUNCHY_DEBUG
                  value: "false"