kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: podinfo
spec:
  ingressClassName: __GLASS_INGRESS_CLASS__
  rules:
    - host: podinfo.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podinfo
                port:
                  name: http
