---
apiVersion: v1
kind: Secret
metadata:
  name: dex
stringData:
  config.yaml: |
    connectors:
  {{- toYaml .Values.idp.connectors | nindent 4}}
    enablePasswordDB: false
    grpc:
      addr: 0.0.0.0:5557
      reflection: true
      tlsCert: ""
      tlsKey: ""
    issuer: https://{{ include "dex.host" . }}
    oauth2:
      skipApprovalScreen: true
    staticClients:
    - id: vkp
      name: VKP
      redirectURIs:
      - https://{{ include "console.host" . }}/oauth2/callback
      secretEnv: CLIENT_SECRET_VKP
    storage:
      config:
        inCluster: true
      type: kubernetes
