apiVersion: paas.dcas.dev/v1alpha1
kind: ClusterAddon
metadata:
  labels:
    app.kubernetes.io/name: clusteraddon
    app.kubernetes.io/instance: clusteraddon-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: clusteraddon-sample
spec:
  # TODO(user): Add fields here
