apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- with .Values.global.ingress.annotations }}
{{- toYaml . | nindent 4 }}
{{- end }}
  name: dex
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  tls:
    - hosts:
        - dex.{{ .Values.global.ingress.domain }}
      secretName: tls-dex
  rules:
    - host: dex.{{ .Values.global.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: dex
                port:
                  number: 5556
---
apiVersion: v1
kind: Secret
metadata:
  name: dex
stringData:
  config.yaml: |
    connectors:
  {{- toYaml .Values.idp.connectors | nindent 4}}
    enablePasswordDB: false
    grpc:
      addr: 0.0.0.0:5557
      reflection: true
      tlsCert: ""
      tlsKey: ""
    issuer: https://dex.{{ .Values.global.ingress.domain }}
    oauth2:
      skipApprovalScreen: true
    staticClients:
    - id: vkp
      name: VKP
      redirectURIs:
      - https://vkp.{{ .Values.global.ingress.domain }}/oauth2/callback
      secretEnv: CLIENT_SECRET_VKP
    storage:
      config:
        inCluster: true
      type: kubernetes