---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: vkp
{{- with .Values.global.ingress.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "vkp.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  tls:
    - hosts:
        - {{ include "console.host" . }}
      secretName: {{ .Values.global.ingress.tlsSecret }}
  rules:
    - host: {{ include "console.host" . }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: apiserver
                port:
                  name: web
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- with .Values.global.ingress.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
  name: dex
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  tls:
    - hosts:
        - {{ include "dex.host" . }}
      secretName: {{ .Values.dex.ingress.tlsSecret }}
  rules:
    - host: {{ include "dex.host" . }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: dex
                port:
                  number: 5556
