{{- if .Values.vkp.certificates.issuer.create }}
apiVersion: cert-manager.io/v1
kind: {{ .Values.vkp.certificates.issuer.kind }}
metadata:
  name: {{ .Values.vkp.certificates.issuer.name }}
  namespace: {{ .Values.vkp.certificates.certManagerNamespace }}
spec:
  selfSigned: {}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vkp-root-ca
  namespace: {{ .Values.vkp.certificates.certManagerNamespace }}
spec:
  isCA: true
  commonName: VKP Root Certificate Authority
  secretName: vkp-root-ca
  duration: 87660h0m0s
  renewBefore: 2190h0m0s
  privateKey:
    algorithm: ECDSA
  issuerRef:
    name: {{ .Values.vkp.certificates.issuer.name }}
    kind: {{ .Values.vkp.certificates.issuer.kind }}
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vkp-identity
spec:
  ca:
    secretName: vkp-root-ca
