{{- if (not .Values.idp.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dex.secret" . }}
stringData:
  DEX_CLIENT_SECRET: {{ .Values.idp.clientSecret }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.idp.cookieSecret }}
{{- end }}