apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "web.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web.labels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: web
    spec:
      {{- if .Values.dex.podSecurityContext }}
      securityContext: {{ toYaml .Values.dex.podSecurityContext | nindent 8 }}
      {{- end }}
      serviceAccountName: web
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.global.caSecret | default .Values.global.ingress.tlsSecret }}
      containers:
        - name: web
          image: {{ .Values.web.image }}
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /var/run/secrets/paas.dcas.dev/tls
              name: tls
              readOnly: true
{{- if .Values.web.containerSecurityContext }}
          securityContext: {{ toYaml .Values.web.containerSecurityContext | nindent 10 }}
{{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
{{ toYaml .Values.dex.resources | indent 12 }}
        - name: oauth-proxy
          image: {{ .Values.oauthProxy.image }}
          args:
            - --http-address=:8079
            - --provider=oidc
            - --client-id=vkp
            - --email-domain=*
            - --oidc-issuer-url=https://dex.{{ .Values.global.ingress.domain }}
            - --redirect-url=https://vkp.{{ .Values.global.ingress.domain }}/oauth2/callback
            - --prefer-email-to-user=true
            - --cookie-secure=true
            - --cookie-refresh=2h
            - --code-challenge-method=S256
            - --upstream=http://localhost:8080
            - --scope=openid profile email groups
          env:
            - name: SSL_CERT_FILE
              value: /var/run/secrets/paas.dcas.dev/tls/ca.crt
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.idp.existingSecret | default "vkp-common" }}
                  key: DEX_CLIENT_SECRET
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.idp.existingSecret | default "vkp-common" }}
                  key: OAUTH2_PROXY_COOKIE_SECRET
          ports:
            - containerPort: 8079
              name: web
              protocol: TCP
          volumeMounts:
            - mountPath: /var/run/secrets/paas.dcas.dev/tls
              name: tls
              readOnly: true
{{- if .Values.oauthProxy.containerSecurityContext }}
          securityContext: {{ toYaml .Values.oauthProxy.containerSecurityContext | nindent 10 }}
{{- end }}
          resources:
{{ toYaml .Values.oauthProxy.resources | indent 12 }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: web
  annotations:
{{- with .Values.global.ingress.annotations }}
{{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.ingressClassName }}
  tls:
    - hosts:
        - vkp.{{ .Values.global.ingress.domain }}
      secretName: {{ .Values.global.ingress.tlsSecret }}
  rules:
    - host: vkp.{{ .Values.global.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: web
---
kind: Service
apiVersion: v1
metadata:
  name: web
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
  selector:
    {{- include "web.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web