apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-metrics-proxy
spec:
  dnsNames:
    - metrics-proxy
    - metrics-proxy.vkp-system
    - metrics-proxy.vkp-system.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: vkp-identity
  secretName: tls-metrics-proxy
  duration: 8760h0m0s
  privateKey:
    algorithm: ECDSA
  renewBefore: 2190h0m0s
  usages:
    - digital signature
    - key encipherment
    - server auth
