apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-proxy
  labels:
    app.kubernetes.io/name: vkp
    app.kubernetes.io/component: metrics-proxy
    app.kubernetes.io/instance: vkp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vkp
      app.kubernetes.io/component: metrics-proxy
      app.kubernetes.io/instance: vkp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vkp
        app.kubernetes.io/component: metrics-proxy
        app.kubernetes.io/instance: vkp
      annotations:
        kubectl.kubernetes.io/default-container: metrics-proxy
    spec:
      volumes:
        - name: pki
          secret:
            secretName: tls-metrics-proxy
      containers:
        - name: metrics-proxy
          image: vkp/metrics-proxy
          args:
            - --v=10
            - --port=8443
            - --prometheus-url=http://prometheus-olm-prometheus.monitoring.svc.cluster.local:9090
            - --tls-cert-file=/var/run/secrets/paas.dcas.dev/pki/tls.crt
            - --tls-key-file=/var/run/secrets/paas.dcas.dev/pki/tls.key
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: SSL_CERT_FILE
              value: /var/run/secrets/paas.dcas.dev/pki/ca.crt
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 8443
              name: web
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
            runAsGroup: 0
            runAsNonRoot: true
            runAsUser: 12848
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8444
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /livez
              port: 8444
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /var/run/secrets/paas.dcas.dev/pki
              name: pki
              readOnly: true
