kind: Service
apiVersion: v1
metadata:
  name: metrics-proxy
  labels:
    app.kubernetes.io/name: vkp
    app.kubernetes.io/component: metrics-proxy
    app.kubernetes.io/instance: vkp
spec:
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 443
      targetPort: web
  selector:
    app.kubernetes.io/name: vkp
    app.kubernetes.io/component: metrics-proxy
    app.kubernetes.io/instance: vkp