apiVersion: paas.dcas.dev/v1alpha1
kind: Platform
metadata:
  name: cluster
spec:
  namespace: glass-system
  prometheusURL: http://prometheus-olm-prometheus.monitoring.svc.cluster.local:9090
  domain: 192-168-49-2.nip.io
  imagePullPolicy: Never
  ingressClassName: nginx
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: iss-kube
    secretRef:
      name: tls-vpk
  dex:
    ingress:
      secretRef:
        name: tls-dex
  apiServer:
    image: dev.local/kube-glass/apiserver:latest
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    oauthProxy:
      image: harbor.dcas.dev/quay.io/oauth2-proxy/oauth2-proxy:v7.4.0-amd64
      imagePullPolicy: IfNotPresent
