---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiserver-role
rules:
  - apiGroups:
      - paas.dcas.dev
    resources:
      - clusters
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
  - apiGroups:
      - paas.dcas.dev
    resources:
      - clusteraddonbindings
      - clusteraddonbindings/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - paas.dcas.dev
    resources:
      - clusteraddons
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - paas.dcas.dev
    resources:
      - tenants
      - tenants/status
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get