releaseOverride: apiserver
image:
  pullPolicy: Never
args:
  - --v=5
  - --prometheus-url=http://prometheus-olm-prometheus.monitoring.svc.cluster.local:9090
  - --prometheus-config-file=/etc/kube-glass/config/prometheus.yaml
  - --dex-url=https://dex.192-168-49-2.nip.io
env:
  API_LOG_LEVEL: 5
  API_METRICS_PROMETHEUS_ADDR: http://prometheus-olm-prometheus.monitoring.svc.cluster.local:9090
  PAAS_IDP_URL: https://dex.192-168-49-2.nip.io
ingress:
  tls:
    secretName: tls-apiserver
  annotations:
    cert-manager.io/cluster-issuer: iss-kube
  className: nginx
  path: /api
livenessProbe:
  path: /livez
  port: 8081
readinessProbe:
  path: /readyz
  port: 8081
rollme: false
service:
  url: https://glass.192-168-49-2.nip.io
  internalPort: 8079
serviceAccount:
  create: false
  name: apiserver
volumes:
  - name: tls
    mountPath: /var/run/secrets/dcas.dev/tls
    config:
      secret:
        secretName: tls-apiserver
  - name: config
    mountPath: /etc/kube-glass/config
    config:
      configMap:
        name: glass-apiserver-config
sidecars:
  - name: oauth-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0-amd64
    ports:
      - containerPort: 8079
        name: public
    volumeMounts:
      - name: tls
        mountPath: /var/run/secrets/dcas.dev/tls
        readOnly: true
    args:
      - --http-address=:8079
      - --provider=oidc
      - --client-id=glass
      - --client-secret=password
      - --email-domain=*
      - --oidc-issuer-url=https://dex.192-168-49-2.nip.io
      - --redirect-url=https://glass.192-168-49-2.nip.io/oauth2/callback
      - --prefer-email-to-user=true
      - --cookie-secure=true
      - --cookie-secret=q4kE_9htyXtMQDgfSkRJcMTxwLCXLjHKFLPGHCbcOgg=
      - --cookie-refresh=2h
      - --code-challenge-method=S256
      - --upstream=http://localhost:8080
      - --scope=openid profile email groups
    env:
      - name: SSL_CERT_FILE
        value: /var/run/secrets/dcas.dev/tls/ca.crt