apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: operator
#requires:
#  - path: ../vcluster-plugin-sync/skaffold.yaml
#    configs:
#      - vcluster-plugin-sync
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: dev.local/kube-glass/vcluster-plugin-sync
    ko:
      fromImage: harbor.dcas.dev/registry.gitlab.com/av1o/helm-install-image:v3-1.25
      main: ../vcluster-plugin-sync/cmd/sync/
      dir: ../vcluster-plugin-sync
      dependencies:
        paths:
          - ../vcluster-plugin-sync/cmd/
          - ../vcluster-plugin-sync/internal/
          - ../vcluster-plugin-sync/go.mod
          - ../vcluster-plugin-sync/go.sum
  - image: controller
    ko:
      fromImage: harbor.dcas.dev/gcr.io/distroless/static:nonroot
      dependencies:
        paths:
          - api/
          - controllers/
          - main.go
          - go.mod
          - go.sum
  local:
    push: false
deploy:
  kustomize:
    paths:
    - config/default
