apiVersion: skaffold/v3
kind: Config
metadata:
  name: web
manifests:
  helm:
    releases:
      - name: web-proxy
        remoteChart: https://charts.bitnami.com/bitnami/nginx-13.2.13.tgz
        valuesFiles:
          - k8s/values.yaml
        namespace: glass-system
        skipBuildDependencies: true
        upgradeOnChange: true
deploy:
  helm: {}
  kubeContext: minikube
